# Generated by Django 3.2.5 on 2021-08-08 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(help_text='اکونٹ کا نام درج کریں', max_length=200)),
                ('phone_number', models.CharField(blank=True, help_text='۔۔۔اکاؤنٹ کا فون نمبر درج کریں', max_length=11, null=True)),
                ('address', models.CharField(blank=True, help_text='اکاؤنٹ کا پتہ درج کریں', max_length=200, null=True)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('transaction_type', models.CharField(blank=True, choices=[('Credit', 'Credit'), ('Debit', 'Debit')], default='Credit', help_text='رقم کی قسم: CR یا DR', max_length=32, null=True)),
                ('balance', models.FloatField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('refernce_number', models.CharField(blank=True, default=django.db.models.fields.AutoField, max_length=366, null=True, unique=True)),
                ('transaction_detail', models.CharField(default='', max_length=210)),
                ('transaction_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], help_text='رقم کی قسم: کریڈٹ یا ڈیبٹ', max_length=32)),
                ('amount', models.FloatField(default=0, null=True)),
                ('balance_after_transaction', models.FloatField(default=0, null=True)),
                ('slip', models.ImageField(blank=True, default='html.png', null=True, upload_to='uploads/')),
                ('account', models.ForeignKey(blank=True, default=0, help_text='وہ کھاتہ جہاں سے رقم جمع ہو', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_account', to='mykhaatabook.account')),
                ('bank', models.ForeignKey(blank=True, default=0, help_text='اکاؤنٹ جس میں رقم جمع کی جائے گی', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_bank', to='mykhaatabook.account')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='AccountsBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(help_text='اکونٹ کا نام درج کریں', max_length=200)),
                ('book_type', models.CharField(choices=[('1', 'Simple'), ('2', 'Clearing'), ('3', 'Hawala'), ('4', 'Bank')], help_text='اکونٹ کی قسم: sm یا cl', max_length=32)),
                ('book_created_date', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-book_created_date'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='book',
            field=models.ForeignKey(default=0, help_text='وہ کھاتہ جہاں سے رقم جمع ہو', max_length=266, null=True, on_delete=django.db.models.deletion.CASCADE, to='mykhaatabook.accountsbook'),
        ),
        migrations.AddField(
            model_name='account',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
