# Generated by Django 3.2.5 on 2021-08-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mykhaatabook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsbook',
            name='book_type',
            field=models.CharField(choices=[('1', 'Simple'), ('2', 'Clearing'), ('3', 'Hawala'), ('4', 'Bank'), ('5', 'Lahore')], help_text='اکونٹ کی قسم: sm یا cl', max_length=32),
        ),
    ]
