# Generated by Django 3.2.5 on 2021-08-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mykhaatabook', '0002_alter_accountsbook_book_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='book',
            field=models.CharField(default=0, help_text='وہ کھاتہ جہاں سے رقم جمع ہو', max_length=266, null=True),
        ),
    ]
