# Generated by Django 3.2.5 on 2021-08-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mykhaatabook', '0003_alter_account_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='book',
            field=models.CharField(choices=[('1', 'Simple'), ('2', 'Clearing'), ('3', 'Hawala'), ('4', 'Bank'), ('5', 'Lahore')], default='Simple', help_text='وہ کھاتہ جہاں سے رقم جمع ہو', max_length=266, null=True),
        ),
    ]
