# Generated by Django 3.2.5 on 2021-08-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mykhaatabook', '0004_alter_account_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='book',
            field=models.CharField(choices=[('1', 'Simple'), ('2', 'Clearing'), ('3', 'Hawala'), ('4', 'Bank'), ('5', 'Lahore'), ('6', 'Cash')], default='Simple', help_text='وہ کھاتہ جہاں سے رقم جمع ہو', max_length=266, null=True),
        ),
        migrations.AlterField(
            model_name='accountsbook',
            name='book_type',
            field=models.CharField(choices=[('1', 'Simple'), ('2', 'Clearing'), ('3', 'Hawala'), ('4', 'Bank'), ('5', 'Lahore'), ('6', 'Cash')], help_text='اکونٹ کی قسم: sm یا cl', max_length=32),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='refernce_number',
            field=models.CharField(auto_created=True, blank=True, default='000000', max_length=366, null=True, unique=True),
        ),
    ]
