# Generated by Django 3.2.5 on 2021-08-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mykhaatabook', '0005_auto_20210810_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='book',
            field=models.CharField(choices=[('1', 'Simple'), ('2', 'Clearing'), ('3', 'Hawala'), ('4', 'Bank'), ('5', 'Lahore'), ('6', 'Cash'), ('7', 'Qarz'), ('8', 'Iran'), ('9', 'Gadi_Kharcha'), ('10', 'Taftan')], default='Simple', help_text='وہ کھاتہ جہاں سے رقم جمع ہو', max_length=266, null=True),
        ),
        migrations.AlterField(
            model_name='accountsbook',
            name='book_type',
            field=models.CharField(choices=[('1', 'Simple'), ('2', 'Clearing'), ('3', 'Hawala'), ('4', 'Bank'), ('5', 'Lahore'), ('6', 'Cash'), ('7', 'Qarz'), ('8', 'Iran'), ('9', 'Gadi_Kharcha'), ('10', 'Taftan')], help_text='اکونٹ کی قسم: sm یا cl', max_length=32),
        ),
    ]
