# Generated by Django 3.2.5 on 2021-08-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mykhaatabook', '0007_auto_20210814_0017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='account',
            name='date_created',
            field=models.DateField(),
        ),
    ]
