# Generated by Django 3.2.5 on 2021-08-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mykhaatabook', '0008_auto_20210826_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
