# Generated by Django 3.2.5 on 2021-08-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mykhaatabook', '0013_auto_20210829_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='slip',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
