# Generated by Django 3.2.7 on 2022-01-12 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mykhaatabook', '0015_alter_accountsbook_book_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, default=0, help_text='وہ کھاتہ جہاں سے رقم جمع ہو', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_account', to='mykhaatabook.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bank',
            field=models.ForeignKey(blank=True, default=0, help_text='اکاؤنٹ جس میں رقم جمع کی جائے گی', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_account', to='mykhaatabook.account'),
        ),
    ]
